### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by lele1894** [Misaka-blog/MisakaLinuxToolbox#16]
V2ray.Fun

ERROR: This script has been DISCARDED, please switch to fhs-install-v2ray project.
HOW TO USE: https://github.com/v2fly/fhs-install-v2ray
TO MIGRATE: https://github.com/v2fly/fhs-install-v2ray/wiki/Migrate-from-the-old-script-to-this

**Comment by misakano7545** [comment]
@lele1894 是V2ray.Fun面板吗

**Comment by lele1894** [comment]
回复那么快~是V2ray.Fun

**Comment by misakano7545** [comment]
@lele1894 能提供下截图吗，因为我在本地环境没复现出问题

**Comment by lele1894** [comment]
![QQ截图20220327153209](https://user-images.githubusercontent.com/11767608/160271552-b9a72023-7d65-4221-a40d-b5cbf7fa17e4.png)
