### ISSUE TITLE
🤔

### ISSUE THREAD

**Issue by hhxie70** [Misaka-blog/MisakaLinuxToolbox#17]

**Comment by misakano7545** [comment]
@hhxie70 如果持续提出无意义Issues，我们可以考虑将你封禁

**Comment by hhxie70** [comment]
我刚玩并不清楚点了什么，能说明一下吗？可能是误点了，应该是哪里有问题?,我确实是小白不懂

Misaka No ***@***.***> 于 2022年4月1日周五 下午5:50写道：
