### ISSUE TITLE
考虑使用 screenfetch 等成熟方案进行环境检测吗？

### ISSUE THREAD

**Issue by Misaka-0x447f** [Misaka-blog/MisakaLinuxToolbox#2]
https://github.com/Misaka-blog/MisakaLinuxToolbox/blob/0369ec68e3d64f72b2757454839f91f1a020b973/MisakaToolbox.sh#L197

**Comment by misakano7545** [comment]
你要是有好的代码可以考虑给我pr下（（（

**Comment by Misaka-0x447f** [comment]
> 你要是有好的代码可以考虑给我pr下（（（

不，就只是直接调用 screenfetch 这个包就可以打出服务器信息了呀。

**Comment by Misaka-0x447f** [comment]
![image](https://user-images.githubusercontent.com/15797507/147830114-63a5b173-34b8-4dc1-979a-d26cfb0b232c.png)
*大概是说替代显示那部分，而不是发行版检测那部分

**Comment by misakano7545** [comment]
> ![image](https://user-images.githubusercontent.com/15797507/147830114-63a5b173-34b8-4dc1-979a-d26cfb0b232c.png) *大概是说替代显示那部分，而不是发行版检测那部分

主要是不懂怎么提取出里面的结果

**Comment by Misaka-0x447f** [comment]
> > ![image](https://user-images.githubusercontent.com/15797507/147830114-63a5b173-34b8-4dc1-979a-d26cfb0b232c.png) *大概是说替代显示那部分，而不是发行版检测那部分
> 
> 主要是不懂怎么提取出里面的结果

提取到变量里再处理吧...

![image](https://user-images.githubusercontent.com/15797507/147830373-1c9474eb-365d-466b-b5d1-9caf530a91d1.png)

或者直接用点正经编程语言？nodejs for eg?

**Comment by misakano7545** [comment]
> > > ![image](https://user-images.githubusercontent.com/15797507/147830114-63a5b173-34b8-4dc1-979a-d26cfb0b232c.png) *大概是说替代显示那部分，而不是发行版检测那部分
> > 
> > 
> > 主要是不懂怎么提取出里面的结果
> 
> 提取到变量里再处理吧...
> 
> ![image](https://user-images.githubusercontent.com/15797507/147830373-1c9474eb-365d-466b-b5d1-9caf530a91d1.png)
> 
> 或者直接用点正经编程语言？nodejs for eg?

但是这个是shell脚本，不是编程程序

**Comment by misakano7545** [comment]
而且要针对每一行进行处理

**Comment by misakano7545** [comment]
![image](https://user-images.githubusercontent.com/96560028/147830566-51a4c189-eb2e-432b-9d87-5ca30e5e3ad2.png)

用neofetch的话，实现这样的处理难度有些大

**Comment by Misaka-0x447f** [comment]
好吧好吧，我就只是说 vps 信息那个 block。。。不重要。
