### ISSUE TITLE
运行时依然报错

### ISSUE THREAD

**Issue by IsaacWangTT** [Misaka-blog/MisakaLinuxToolbox#24]
MisakaToolbox.sh: line 417: syntax error near unexpected token \`)'
MisakaToolbox.sh: line 417: `   0) menu ;;'

**Comment by Lemonawa** [comment]
> MisakaToolbox.sh: line 417: syntax error near unexpected token `)' MisakaToolbox.sh: line 417: ` 0) menu ;;'

更新

**Comment by IsaacWangTT** [comment]
> > MisakaToolbox.sh: line 417: syntax error near unexpected token `)' MisakaToolbox.sh: line 417: ` 0) menu ;;'
> 
> 更新 等刷新缓存

okok没问题了:)
