### ISSUE TITLE
工具箱功能提议

### ISSUE THREAD

**Issue by misakano7545** [Misaka-blog/MisakaLinuxToolbox#3]
如你有添加功能的需求，可以到这个issues跟帖提出自己的需求。我看到后会根据自己的能力尽力满足你的需求！

**Comment by 2ndMessiah** [comment]
脚本非常不错 方便多了

建议增加调整时区的功能~谢谢

`sudo timedatectl set-timezone "Asia/Shanghai"`

**Comment by misakano7545** [comment]
@2ndMessiah 感觉没必要吧

**Comment by 2ndMessiah** [comment]
好的👌🏻

就是crontab的时候方便掐时间

Misaka No ***@***.***> 于 2022年2月5日周六 12:35写道：

**Comment by misakano7545** [comment]
@2ndMessiah 这个就一行命令就行了，感觉不用加到工具箱

**Comment by spiritLHL** [comment]
有反代脚本就好了，反代一些网站

**Comment by spiritLHL** [comment]
还有搭建socks5代理的脚本或者面板

**Comment by misakano7545** [comment]
> 还有搭建socks5代理的脚本或者面板

可以提供一下仓库地址吗

**Comment by spiritLHLS** [comment]
curl https://raw.githubusercontent.com/zhucaidan/mtr_trace/main/mtr_trace.sh |bash
建议添加路由测试
