### ISSUE TITLE
建议把全部脚本内的raw.githubusercontent.com换成jsdelivr

### ISSUE THREAD

**Issue by Lemonawa** [Misaka-blog/MisakaLinuxToolbox#4]
![图片](https://user-images.githubusercontent.com/69106050/148672482-96ce5472-51e0-4e72-84c9-ee57f0b7e0bb.png)
国内机太痛苦了

**Comment by misakano7545** [comment]
可以，到时候等我有时间我做下

**Comment by Lemonawa** [comment]
#5

**Comment by qeqeq1** [comment]
国内jsdelivr效果也欠佳，本站的有没有可靠的方案了

**Comment by misakano7545** [comment]
> 国内jsdelivr效果也欠佳，不知道有没有可靠的方案了

自建了，但是维护量翻倍

**Comment by Lemonawa** [comment]
> > 国内jsdelivr效果也欠佳，不知道有没有可靠的方案了
> 
> 自建了，但是维护量翻倍

反代？

**Comment by misakano7545** [comment]
> > > 国内jsdelivr效果也欠佳，不知道有没有可靠的方案了
> > 
> > 
> > 自建了，但是维护量翻倍
> 
> 反代？

对，我觉得用workers反代，用的人多会出触发每天10w请求的限制

**Comment by Lemonawa** [comment]
> > > > 国内jsdelivr效果也欠佳，不知道有没有可靠的方案了
> > > 
> > > 
> > > 自建了，但是维护量翻倍
> > 
> > 
> > 反代？
> 
> 对，我觉得用workers反代，用的人多会出触发每天10w请求的限制

其实有个好东西  
fastgit.org  
有raw加速的
```
https://raw.fastgit.org/Misaka-blog/MisakaLinuxToolbox/master/MisakaToolbox.sh
```
速度还不错

**Comment by misakano7545** [comment]
> > > > > 国内jsdelivr效果也欠佳，不知道有没有可靠的方案了
> > > > 
> > > > 
> > > > 自建了，但是维护量翻倍
> > > 
> > > 
> > > 反代？
> > 
> > 
> > 对，我觉得用workers反代，用的人多会出触发每天10w请求的限制
> 
> 其实有个好东西 fastgit.org 有raw加速的
> 
> ```
> https://raw.fastgit.org/Misaka-blog/MisakaLinuxToolbox/master/MisakaToolbox.sh
> ```
> 
> 速度还不错

这个我记得是跳转到raw github
