### ISSUE TITLE
安装Trojan面板与V2ray.Fun面板遇到错误

### ISSUE THREAD

**Issue by mslxi** [Misaka-blog/MisakaLinuxToolbox#8]
安装 Trojan 面板遇到错误：Error: Oh My Zsh can't be loaded from: bash. You need to run zsh instead，脚本没有指定#!/bin/bash
安装V2ray.Fun面板遇到错误：ERROR: This script has been DISCARDED, please switch to fhs-install-v2ray project

**Comment by misakano7545** [comment]
自己去GitHub找对应的上游
